### ISSUE TITLE
When I turn off the wifi and turn it on again it can't connect to wifi anymore!

### ISSUE THREAD

**Issue by cata0309** [Alexander88207/RTL-Driver-Installer#21]
**Describe the bug**
Whenever it happens to not need wifi I disable it, but I noticed that after turning it on again it won't connect to the same network anymore

**Desktop (please complete the following information):**
 - OS: Solus 4 Fortitude
Linux-current 5.0.16-116

**Comment by cata0309** [comment]
I also noticed what is causing the bug. When you are disabling it the process itself, wifi, doesn't run anymore. I made a simple script for restarting wifi service: `nmcli radio wifi off && sleep 5 && nmcli radio wifi on`, but I need to know how to solve it without this workaround

**Comment by Alexander88207** [comment]
Hello @cata0309 ,

to understand your problem: You turn off your wifi, and when you turn it on again but it doesn't automatically connect to your network?

**Comment by Alexander88207** [comment]
Since there has been no answer for more than a month, I now close this issue.

**Comment by cata0309** [comment]
I made a script to restart the network manager
It would be awesome if you could implement something to make the driver work after a kernel update and not reinstall it. I had some important exams to pass and I was very busy, sorry

**Comment by Alexander88207** [comment]
This is not possible for things like your case you need use dkms but solus dont have dkms
